UI.Label("discord: riquezerah")
UI.Label("discord: riquezerah")
UI.Label("discord: riquezerah")
UI.Label("discord: riquezerah")
UI.Label("discord: riquezerah")
UI.Label("discord: riquezerah")
UI.Label("discord: riquezerah")
UI.Label("discord: riquezerah")
UI.Label("discord: riquezerah")
UI.Label("discord: riquezerah")
warn("Você foi desconectado")
schedule(2500, function()
g_game.safeLogout()
